### ISSUE TITLE
Βήμα 8 - labels

### ISSUE THREAD

**Issue by Con-Fou** [slp-ntua/patreco-lab-support-19-20#34]
Στο βήμα 8 που εκπαιδεύουμε 3 μοντέλα ένα για κάθε άξονα(valance, energy, danceability), πώς γίνεται η ταξινόμηση σε κλάσεις, ενώ τα labels είναι δεκαδικοί; Θεωρούμε ότι είναι δυαδικό πρόβλημα ταξινόμησης, όπου κάτω από 0.5 αντιστοιχεί σε 0 και πάνω από αυτό σε ένα;

**Comment by georgepar** [comment]
Οχι δε θέλετε να κάνετε ταξινόμηση. Θέλετε να κάνετε παλινδρόμηση (regression) στις πραγματικές τιμές
